import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

const sources = [
  "node_modules/@mantine/core/styles.css",
  "node_modules/@mantine/charts/styles.css",
];

let css = "";
const missing = [];
for (const rel of sources) {
  const p = path.join(root, rel);
  if (fs.existsSync(p)) {
    css += fs.readFileSync(p, "utf8") + "\n";
  } else {
    missing.push(rel);
  }
}

if (missing.length) {
  console.error(
    "Missing CSS sources (run `npm install` first): " + missing.join(", ")
  );
  process.exit(1);
}

// Compact: collapse runs of blank/whitespace-only lines.
css = css
  .split("\n")
  .filter((l) => l.trim().length > 0)
  .join("\n");

const out = path.join(root, "src", "styles.generated.mjs");
const content =
  `// AUTO-GENERATED by scripts/embed-styles.mjs. Do not edit by hand.\n` +
  `// Embeds @mantine styles so the exported HTML is fully self-contained.\n` +
  `export default ${JSON.stringify(css)};\n`;

fs.writeFileSync(out, content, "utf8");
console.log(`Wrote ${path.relative(root, out)} (${css.length} chars)`);
